project: 
  type: book

book: 
  page-navigation: true
  title: "UW FISH 572: Principles and applications of fisheries-independent surveys" 
  site-url: "https://afsc-gap-products.github.io/UW-FISH572/" 
  repo-url: "https://github.com/afsc-gap-products/UW-FISH572"
  repo-actions: [edit, source, issue]
  favicon: images/favicon.png
  downloads: [pdf, docx]
  search: true
  author:
    - name: Dr. Stan Kotwicki
      email: Stan.Kotwicki AT noaa.gov 
      orcid: 0000-0002-6112-5021
      note: https://github.com/StanKotwicki-NOAA
      affiliations:
        - name: NOAA Fisheries Alaska Fisheries Science Center
          department: Groundfish Assessment Program
    - name: Dr. Allan Hicks
      email: Allan.Hicks AT iphc.int 
      note: https://github.com/AllanHicks-IPHC
      affiliations:
        - name: International Pacific Halibut Commission
    - name: Dr. Lewis Barnett
      email: Lewis.Barnett AT noaa.gov 
      note: https://github.com/Lewis-Barnett-NOAA
      affiliations:
        - name: NOAA Fisheries Alaska Fisheries Science Center
          department: Groundfish Assessment Program
    - name: Dr. Sophia Wassermann
      email: Sophia.Wassermann AT noaa.gov 
      orcid: 0000-0002-4323-5227
      note: https://github.com/sowasser
      affiliations:
        - name: NOAA Fisheries Alaska Fisheries Science Center
          department: Groundfish Assessment Program
    - name: Emily Markowitz
      email: Emily.Markowitz AT noaa.gov 
      orcid: 0000-0001-5757-4230
      note: https://github.com/EmilyMarkowitz-NOAA
      affiliations:
        - name: NOAA Fisheries Alaska Fisheries Science Center
          department: Groundfish Assessment Program
  chapters:
    - index.qmd
    - content/course-info.qmd
    - content/coursework.qmd
    - content/faq.qmd
    - content/resources.qmd
    - content/references.qmd

  page-footer:
    right: "[U.S. Department of Commerce](https://www.commerce.gov/) | [National Oceanographic and Atmospheric Administration](https://www.noaa.gov) | [NOAA Fisheries](https://www.fisheries.noaa.gov/)" 
    left: "&copy; CC-1.0"
  
  sidebar:
    background: "#D9E3E4"
    logo: images/favicon.png
    favicon: images/favicon.png
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://afsc-gap-products.github.io/UW-FISH572/
        text: "UW-FISH572"
    style: "docked"
    search: true
    collapse-level: 2

bibliography: [content/references.bib]
csl: content/references.csl
# csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa-no-ampersand.csl
# bibliography: https://raw.githubusercontent.com/afsc-gap-products/citations/main/cite/bibliography.bib

execute:
  echo: false
  # eval: true
  error: false
  message: false
  comment: false
  warning: false
  code-overflow: wrap
  freeze: auto
  
format:
  titlepage-pdf:
    documentclass: scrbook
    classoption: ["oneside", "open=any"]
    titlepage: "plain"
    keep-tex: true
  docx:
    toc: true
    toc-depth: 2
    reference-doc: template.docx
    always_allow_html: true
  html:
    theme: [cosmo, assets/theme.scss] 
    toc: true
    toc-depth: 3

filters:
  - assets/include-files.lua
  - quarto

# Comment next 2 lines if the PDF is having trouble
metadata-files:
  - _frontmatter.yml
 
env:
  QUARTO_EXECUTE_FREEZE: false
  