on:
  push:
    branches: main

name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # ---------- 1. Checkout repo ----------
      - name: Check out repository
        uses: actions/checkout@v4

      # ---------- 2. Install system dependencies ----------
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcairo2-dev \
            libfreetype6-dev \
            libfontconfig1-dev \
            libmagick++-dev \
            libgl1-mesa-dev \
            libglu1-mesa-dev \
            libglpk-dev \
            libcurl4-openssl-dev \
            libxml2-dev \
            pandoc \
            ttf-mscorefonts-ins
